FROM debian:wheezy

MAINTAINER blacktop, https://github.com/blacktop

ENV TINI_VERSION v0.9.0

# Install Bro Required Dependencies
RUN buildDeps='ca-certificates wget' \
  && set -x \
  && echo "[INFO] Installing Dependancies..." \
  && apt-get -qq update \
  && apt-get install -yq $buildDeps --no-install-recommends \
  && echo "Grab tini for signal processing and zombie killing..." \
  && wget -O /usr/local/bin/tini "https://github.com/krallin/tini/releases/download/$TINI_VERSION/tini" \
  && wget -O /usr/local/bin/tini.asc "https://github.com/krallin/tini/releases/download/$TINI_VERSION/tini.asc" \
  && export GNUPGHOME="$(mktemp -d)" \
  && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 6380DC428747F6C393FEACA59A84159D7001A4E5 \
  && gpg --batch --verify /usr/local/bin/tini.asc /usr/local/bin/tini \
  && rm -r "$GNUPGHOME" /usr/local/bin/tini.asc \
  && chmod +x /usr/local/bin/tini \
  && tini -h \
  && echo "[INFO] Installing Bro-IDS..." \
  && wget -qO - http://download.opensuse.org/repositories/network:bro/Debian_8.0/Release.key | apt-key add - \
  && echo 'deb http://download.opensuse.org/repositories/network:/bro/Debian_7.0/ /' \
    >> /etc/apt/sources.list.d/bro.list \
  && apt-get update \
  && apt-get install -y bro \
  && echo "[INFO] Cleaning image to reduce size..." \
  && rm -rf /bro \
  && apt-get purge -y $buildDeps \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install the GeoIPLite Database
COPY /geoip /usr/share/GeoIP/
RUN gunzip /usr/share/GeoIP/GeoLiteCity.dat.gz \
  && rm -f /usr/share/GeoIP/GeoLiteCity.dat.gz \
  && ln -s /usr/share/GeoIP/GeoLiteCity.dat /usr/share/GeoIP/GeoIPCity.dat

ENV PATH /opt/bro/bin:$PATH

# Add PCAP Test Folder
COPY /pcap/heartbleed.pcap /pcap/
VOLUME ["/pcap"]
WORKDIR /pcap

# Add Scripts Folder
COPY /scripts /scripts
COPY /scripts/local.bro /opt/bro/share/bro/site/local.bro

ENTRYPOINT ["tini","--","bro"]

CMD ["-h"]
